// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3P_ihzZeRLVddtvgC6DscZ91o2fkaoNU',
    appId: '1:842564652954:web:3098cdb2fcc3e0da1d3423',
    messagingSenderId: '842564652954',
    projectId: 'moda-rakia',
    authDomain: 'moda-rakia.firebaseapp.com',
    storageBucket: 'moda-rakia.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaSZPpvwW1UaksMEkxzkVxUMPN1nQ0ivw',
    appId: '1:842564652954:android:1d12e331bbd8081a1d3423',
    messagingSenderId: '842564652954',
    projectId: 'moda-rakia',
    storageBucket: 'moda-rakia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVPs_sZiPkPIRhzMKHUC8S8Gicg0YFnVo',
    appId: '1:842564652954:ios:f45efd64171806e51d3423',
    messagingSenderId: '842564652954',
    projectId: 'moda-rakia',
    storageBucket: 'moda-rakia.appspot.com',
    iosBundleId: 'com.example.modaRakiaMine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVPs_sZiPkPIRhzMKHUC8S8Gicg0YFnVo',
    appId: '1:842564652954:ios:c23bd7f24aae71c81d3423',
    messagingSenderId: '842564652954',
    projectId: 'moda-rakia',
    storageBucket: 'moda-rakia.appspot.com',
    iosBundleId: 'com.example.modaRakiaMine.RunnerTests',
  );
}
